### ISSUE TITLE
Checklist Low Hanging Fruit

### ISSUE THREAD

**Issue by devsjors** [sarkis1997/frontend-data#6]
# Welcome to StackEdit!
### Low Hanging Fruit
**Readme**
- [x] Gitignore
- [x]  link to live demo on github pages
- [x]  description
- [x]  concept 
- [x] image
- [x] link to example used to build visualization (screenshots)
- [x] data used (what's done with invalid and empty values?)
- [x] plagiarism and acknowledgements

**Wiki**
- [x] wiki
		- De datums in de wiki zijn November in plaats van Oktober.
- [x]  Is the update pattern (data flow) documented?
		- Update functie is niet gedocumenteerd. In de code zie ik wel dat je eerst alle circles weghaalt en vervolgens weer inlaadt. Dit is niet updaten maar weghalen en enteren. Hier zou ik nog wat tijd aan besteden.
- [x] (link to) functional pattern
		- Duidelijk uitgelegd in het logboek. **Tip:** Ik zou hier echter wel een aparte pagina voor maken in je wiki zodat je het proces makkelijk uit kan leggen tijdens de oplevering

**Concept**
- [x]  Does the visualization makes sense on it's own? (labels, axis, titles)
- [x] What patterns do you see in this visualization. What can a user (viewer) learn?
- [x] Is the visualization build for a target audience? (write in issue)
- [x] How does the data change based on interaction (hide show svg's, data filtering?)

**Code**
Met de code heel goed gewerkt door middel van de modules. Daardoor is het ook goed te volgen. Wel lastig om te 'zien' wat de code doet aangezien er geen live preview is. Code ziet door alle functies er ook heel erg functioneel en dynamisch uit.

**Comment by Razpudding** [comment]
Welcome to StackEdit! 🌈
